allowBuilds:
  "@sentry/cli": true
  esbuild: true
  lightningcss: true
  msw: true
  sharp: true
  supabase: true
  workerd: true

overrides:
  vite: "npm:@voidzero-dev/vite-plus-core@0.2.5"

peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
