/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthSetPasswordRouteImport } from './routes/auth/set-password'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthConfirmRouteImport } from './routes/auth/confirm'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as ProtectedAdminRouteImport } from './routes/_protected/_admin'
import { Route as ProtectedAccountRouteImport } from './routes/_protected/_account'
import { Route as ProtectedAccountsIndexRouteImport } from './routes/_protected/accounts/index'
import { Route as ProtectedAdminUsersRouteImport } from './routes/_protected/_admin/users'
import { Route as ProtectedAdminDashboardRouteImport } from './routes/_protected/_admin/dashboard'
import { Route as ProtectedAccountAccountsRouteImport } from './routes/_protected/_account/accounts'
import { Route as ProtectedAccountAccountsAccountIdIndexRouteImport } from './routes/_protected/_account/accounts/$accountId/index'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSetPasswordRoute = AuthSetPasswordRouteImport.update({
  id: '/auth/set-password',
  path: '/auth/set-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthConfirmRoute = AuthConfirmRouteImport.update({
  id: '/auth/confirm',
  path: '/auth/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedAdminRoute = ProtectedAdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAccountRoute = ProtectedAccountRouteImport.update({
  id: '/_account',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAccountsIndexRoute = ProtectedAccountsIndexRouteImport.update({
  id: '/accounts/',
  path: '/accounts/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAdminUsersRoute = ProtectedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => ProtectedAdminRoute,
} as any)
const ProtectedAdminDashboardRoute = ProtectedAdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProtectedAdminRoute,
} as any)
const ProtectedAccountAccountsRoute =
  ProtectedAccountAccountsRouteImport.update({
    id: '/accounts',
    path: '/accounts',
    getParentRoute: () => ProtectedAccountRoute,
  } as any)
const ProtectedAccountAccountsAccountIdIndexRoute =
  ProtectedAccountAccountsAccountIdIndexRouteImport.update({
    id: '/$accountId/',
    path: '/$accountId/',
    getParentRoute: () => ProtectedAccountAccountsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/set-password': typeof AuthSetPasswordRoute
  '/accounts': typeof ProtectedAccountAccountsRouteWithChildren
  '/dashboard': typeof ProtectedAdminDashboardRoute
  '/users': typeof ProtectedAdminUsersRoute
  '/accounts/': typeof ProtectedAccountsIndexRoute
  '/accounts/$accountId/': typeof ProtectedAccountAccountsAccountIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/set-password': typeof AuthSetPasswordRoute
  '/accounts': typeof ProtectedAccountsIndexRoute
  '/dashboard': typeof ProtectedAdminDashboardRoute
  '/users': typeof ProtectedAdminUsersRoute
  '/accounts/$accountId': typeof ProtectedAccountAccountsAccountIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/_protected/_account': typeof ProtectedAccountRouteWithChildren
  '/_protected/_admin': typeof ProtectedAdminRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/set-password': typeof AuthSetPasswordRoute
  '/_protected/_account/accounts': typeof ProtectedAccountAccountsRouteWithChildren
  '/_protected/_admin/dashboard': typeof ProtectedAdminDashboardRoute
  '/_protected/_admin/users': typeof ProtectedAdminUsersRoute
  '/_protected/accounts/': typeof ProtectedAccountsIndexRoute
  '/_protected/_account/accounts/$accountId/': typeof ProtectedAccountAccountsAccountIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/auth/callback'
    | '/auth/confirm'
    | '/auth/reset-password'
    | '/auth/set-password'
    | '/accounts'
    | '/dashboard'
    | '/users'
    | '/accounts/'
    | '/accounts/$accountId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/auth/callback'
    | '/auth/confirm'
    | '/auth/reset-password'
    | '/auth/set-password'
    | '/accounts'
    | '/dashboard'
    | '/users'
    | '/accounts/$accountId'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/forgot-password'
    | '/login'
    | '/_protected/_account'
    | '/_protected/_admin'
    | '/auth/callback'
    | '/auth/confirm'
    | '/auth/reset-password'
    | '/auth/set-password'
    | '/_protected/_account/accounts'
    | '/_protected/_admin/dashboard'
    | '/_protected/_admin/users'
    | '/_protected/accounts/'
    | '/_protected/_account/accounts/$accountId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthConfirmRoute: typeof AuthConfirmRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSetPasswordRoute: typeof AuthSetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/set-password': {
      id: '/auth/set-password'
      path: '/auth/set-password'
      fullPath: '/auth/set-password'
      preLoaderRoute: typeof AuthSetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/confirm': {
      id: '/auth/confirm'
      path: '/auth/confirm'
      fullPath: '/auth/confirm'
      preLoaderRoute: typeof AuthConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/_admin': {
      id: '/_protected/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedAdminRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/_account': {
      id: '/_protected/_account'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedAccountRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/accounts/': {
      id: '/_protected/accounts/'
      path: '/accounts'
      fullPath: '/accounts/'
      preLoaderRoute: typeof ProtectedAccountsIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/_admin/users': {
      id: '/_protected/_admin/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof ProtectedAdminUsersRouteImport
      parentRoute: typeof ProtectedAdminRoute
    }
    '/_protected/_admin/dashboard': {
      id: '/_protected/_admin/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedAdminDashboardRouteImport
      parentRoute: typeof ProtectedAdminRoute
    }
    '/_protected/_account/accounts': {
      id: '/_protected/_account/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof ProtectedAccountAccountsRouteImport
      parentRoute: typeof ProtectedAccountRoute
    }
    '/_protected/_account/accounts/$accountId/': {
      id: '/_protected/_account/accounts/$accountId/'
      path: '/$accountId'
      fullPath: '/accounts/$accountId/'
      preLoaderRoute: typeof ProtectedAccountAccountsAccountIdIndexRouteImport
      parentRoute: typeof ProtectedAccountAccountsRoute
    }
  }
}

interface ProtectedAccountAccountsRouteChildren {
  ProtectedAccountAccountsAccountIdIndexRoute: typeof ProtectedAccountAccountsAccountIdIndexRoute
}

const ProtectedAccountAccountsRouteChildren: ProtectedAccountAccountsRouteChildren =
  {
    ProtectedAccountAccountsAccountIdIndexRoute:
      ProtectedAccountAccountsAccountIdIndexRoute,
  }

const ProtectedAccountAccountsRouteWithChildren =
  ProtectedAccountAccountsRoute._addFileChildren(
    ProtectedAccountAccountsRouteChildren,
  )

interface ProtectedAccountRouteChildren {
  ProtectedAccountAccountsRoute: typeof ProtectedAccountAccountsRouteWithChildren
}

const ProtectedAccountRouteChildren: ProtectedAccountRouteChildren = {
  ProtectedAccountAccountsRoute: ProtectedAccountAccountsRouteWithChildren,
}

const ProtectedAccountRouteWithChildren =
  ProtectedAccountRoute._addFileChildren(ProtectedAccountRouteChildren)

interface ProtectedAdminRouteChildren {
  ProtectedAdminDashboardRoute: typeof ProtectedAdminDashboardRoute
  ProtectedAdminUsersRoute: typeof ProtectedAdminUsersRoute
}

const ProtectedAdminRouteChildren: ProtectedAdminRouteChildren = {
  ProtectedAdminDashboardRoute: ProtectedAdminDashboardRoute,
  ProtectedAdminUsersRoute: ProtectedAdminUsersRoute,
}

const ProtectedAdminRouteWithChildren = ProtectedAdminRoute._addFileChildren(
  ProtectedAdminRouteChildren,
)

interface ProtectedRouteChildren {
  ProtectedAccountRoute: typeof ProtectedAccountRouteWithChildren
  ProtectedAdminRoute: typeof ProtectedAdminRouteWithChildren
  ProtectedAccountsIndexRoute: typeof ProtectedAccountsIndexRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedAccountRoute: ProtectedAccountRouteWithChildren,
  ProtectedAdminRoute: ProtectedAdminRouteWithChildren,
  ProtectedAccountsIndexRoute: ProtectedAccountsIndexRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthConfirmRoute: AuthConfirmRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSetPasswordRoute: AuthSetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
