/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthSetPasswordRouteImport } from './routes/auth/set-password'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as ProtectedAppRouteImport } from './routes/_protected/_app'
import { Route as ProtectedAppUsersRouteImport } from './routes/_protected/_app/users'
import { Route as ProtectedAppDashboardRouteImport } from './routes/_protected/_app/dashboard'
import { Route as ProtectedAppAccountsRouteImport } from './routes/_protected/_app/accounts'
import { Route as ProtectedAppAccountsIndexRouteImport } from './routes/_protected/_app/accounts/index'
import { Route as ProtectedAppAccountsAccountIdOrdersRouteImport } from './routes/_protected/_app/accounts/$accountId/orders'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSetPasswordRoute = AuthSetPasswordRouteImport.update({
  id: '/auth/set-password',
  path: '/auth/set-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedAppRoute = ProtectedAppRouteImport.update({
  id: '/_app',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAppUsersRoute = ProtectedAppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => ProtectedAppRoute,
} as any)
const ProtectedAppDashboardRoute = ProtectedAppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProtectedAppRoute,
} as any)
const ProtectedAppAccountsRoute = ProtectedAppAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => ProtectedAppRoute,
} as any)
const ProtectedAppAccountsIndexRoute =
  ProtectedAppAccountsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedAppAccountsRoute,
  } as any)
const ProtectedAppAccountsAccountIdOrdersRoute =
  ProtectedAppAccountsAccountIdOrdersRouteImport.update({
    id: '/$accountId/orders',
    path: '/$accountId/orders',
    getParentRoute: () => ProtectedAppAccountsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/set-password': typeof AuthSetPasswordRoute
  '/accounts': typeof ProtectedAppAccountsRouteWithChildren
  '/dashboard': typeof ProtectedAppDashboardRoute
  '/users': typeof ProtectedAppUsersRoute
  '/accounts/': typeof ProtectedAppAccountsIndexRoute
  '/accounts/$accountId/orders': typeof ProtectedAppAccountsAccountIdOrdersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/set-password': typeof AuthSetPasswordRoute
  '/dashboard': typeof ProtectedAppDashboardRoute
  '/users': typeof ProtectedAppUsersRoute
  '/accounts': typeof ProtectedAppAccountsIndexRoute
  '/accounts/$accountId/orders': typeof ProtectedAppAccountsAccountIdOrdersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/_protected/_app': typeof ProtectedAppRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/set-password': typeof AuthSetPasswordRoute
  '/_protected/_app/accounts': typeof ProtectedAppAccountsRouteWithChildren
  '/_protected/_app/dashboard': typeof ProtectedAppDashboardRoute
  '/_protected/_app/users': typeof ProtectedAppUsersRoute
  '/_protected/_app/accounts/': typeof ProtectedAppAccountsIndexRoute
  '/_protected/_app/accounts/$accountId/orders': typeof ProtectedAppAccountsAccountIdOrdersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/auth/callback'
    | '/auth/reset-password'
    | '/auth/set-password'
    | '/accounts'
    | '/dashboard'
    | '/users'
    | '/accounts/'
    | '/accounts/$accountId/orders'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/auth/callback'
    | '/auth/reset-password'
    | '/auth/set-password'
    | '/dashboard'
    | '/users'
    | '/accounts'
    | '/accounts/$accountId/orders'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/forgot-password'
    | '/login'
    | '/_protected/_app'
    | '/auth/callback'
    | '/auth/reset-password'
    | '/auth/set-password'
    | '/_protected/_app/accounts'
    | '/_protected/_app/dashboard'
    | '/_protected/_app/users'
    | '/_protected/_app/accounts/'
    | '/_protected/_app/accounts/$accountId/orders'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSetPasswordRoute: typeof AuthSetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/set-password': {
      id: '/auth/set-password'
      path: '/auth/set-password'
      fullPath: '/auth/set-password'
      preLoaderRoute: typeof AuthSetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/_app': {
      id: '/_protected/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedAppRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/_app/users': {
      id: '/_protected/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof ProtectedAppUsersRouteImport
      parentRoute: typeof ProtectedAppRoute
    }
    '/_protected/_app/dashboard': {
      id: '/_protected/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedAppDashboardRouteImport
      parentRoute: typeof ProtectedAppRoute
    }
    '/_protected/_app/accounts': {
      id: '/_protected/_app/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof ProtectedAppAccountsRouteImport
      parentRoute: typeof ProtectedAppRoute
    }
    '/_protected/_app/accounts/': {
      id: '/_protected/_app/accounts/'
      path: '/'
      fullPath: '/accounts/'
      preLoaderRoute: typeof ProtectedAppAccountsIndexRouteImport
      parentRoute: typeof ProtectedAppAccountsRoute
    }
    '/_protected/_app/accounts/$accountId/orders': {
      id: '/_protected/_app/accounts/$accountId/orders'
      path: '/$accountId/orders'
      fullPath: '/accounts/$accountId/orders'
      preLoaderRoute: typeof ProtectedAppAccountsAccountIdOrdersRouteImport
      parentRoute: typeof ProtectedAppAccountsRoute
    }
  }
}

interface ProtectedAppAccountsRouteChildren {
  ProtectedAppAccountsIndexRoute: typeof ProtectedAppAccountsIndexRoute
  ProtectedAppAccountsAccountIdOrdersRoute: typeof ProtectedAppAccountsAccountIdOrdersRoute
}

const ProtectedAppAccountsRouteChildren: ProtectedAppAccountsRouteChildren = {
  ProtectedAppAccountsIndexRoute: ProtectedAppAccountsIndexRoute,
  ProtectedAppAccountsAccountIdOrdersRoute:
    ProtectedAppAccountsAccountIdOrdersRoute,
}

const ProtectedAppAccountsRouteWithChildren =
  ProtectedAppAccountsRoute._addFileChildren(ProtectedAppAccountsRouteChildren)

interface ProtectedAppRouteChildren {
  ProtectedAppAccountsRoute: typeof ProtectedAppAccountsRouteWithChildren
  ProtectedAppDashboardRoute: typeof ProtectedAppDashboardRoute
  ProtectedAppUsersRoute: typeof ProtectedAppUsersRoute
}

const ProtectedAppRouteChildren: ProtectedAppRouteChildren = {
  ProtectedAppAccountsRoute: ProtectedAppAccountsRouteWithChildren,
  ProtectedAppDashboardRoute: ProtectedAppDashboardRoute,
  ProtectedAppUsersRoute: ProtectedAppUsersRoute,
}

const ProtectedAppRouteWithChildren = ProtectedAppRoute._addFileChildren(
  ProtectedAppRouteChildren,
)

interface ProtectedRouteChildren {
  ProtectedAppRoute: typeof ProtectedAppRouteWithChildren
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedAppRoute: ProtectedAppRouteWithChildren,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSetPasswordRoute: AuthSetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
